### ISSUE TITLE
Add nix-bundle to nixpkgs

### ISSUE THREAD

**Issue by dmjio** [matthewbauer/nix-bundle#11]
Any plan to make this usable from within nixpkgs? Or is it already? Couldn't find it in `nix-repl`

**Comment by matthewbauer** [comment]
Yeah, it's not that easy because we need a reference to nixpkgs within nix-bundle for it to generate correctly. I'll think about ways to do this.

**Comment by bjornfor** [comment]
Seems this can be closed now :-)

https://github.com/NixOS/nixpkgs/pull/25236
