### ISSUE TITLE
Unwanted output when running ./hello

### ISSUE THREAD

**Issue by bjornfor** [matthewbauer/nix-bundle#12]
I did the example from the front-page, but it printed some unwanted noise:

```
$ ./hello 
/tmp/tmpx-2017.04.26T09.58.27Z-c53661af/dat
Hello, world!
```

**Comment by bjornfor** [comment]
This is with nix-bundle just merged to nixpkgs master branch.

**Comment by matthewbauer** [comment]
I can't reproduce this. Are you running on NixOS?

My bet is that something weird is going on with [arx](https://github.com/solidsnack/arx). What that is isn't exactly clear...

**Comment by bjornfor** [comment]
Yeah, that was NixOS 17.03 + nix-bundle from master.

**Comment by bjornfor** [comment]
```
$ ./hello --extract
/home/bfo/forks/nixpkgs2/dat
```

I have no 'tar' alias:

```
$ command -v tar
/run/current-system/sw/bin/tar
```

**Comment by ThibaultLemaire** [comment]
Cannot reproduce with `NixOS 20.09 (Nightingale) x86_64` and nix-bundle `f7417243f7678a23db19589469e10cf67800b391`. Issue solved?

**Comment by matthewbauer** [comment]
Yeah it looks like it.
