### ISSUE TITLE
Executing an AppImage bundled with nix2appimage.sh failing with Segmentation fault.

### ISSUE THREAD

**Issue by 365andreas** [matthewbauer/nix-bundle#24]
https://github.com/matthewbauer/nix-bundle/blob/ffa334943283f8757f720f5f2fd26306b582f200/AppRun.c#L248
https://github.com/matthewbauer/nix-bundle/blob/ffa334943283f8757f720f5f2fd26306b582f200/AppRun.c#L250
Executing AppImages bundled with nix2appimage.sh was failing because those two environment variables were not set.

**Comment by 365andreas** [comment]
I added 
`
if (HOSTNAME != NULL)
        SAVE_ENV_VAR(HOSTNAME);
  if (LC_ALL != NULL)
        SAVE_ENV_VAR(LC_ALL);`

**Comment by probonopd** [comment]
So @365andreas can you use nix2appimage.sh to bundle, e.g., Firefox, and run it on a system that has no NIX tools installed, e.g., a normal Ubuntu Live ISO? Does it work?

**Comment by 365andreas** [comment]
@probonopd Yes my app started normally but had a problem with the fonts so I added some in /{nix-path}/myapp.AppDir/usr/share/fonts manually.
