### ISSUE TITLE
Nix 2 compat

### ISSUE THREAD

**Issue by dtzWill** [matthewbauer/nix-bundle#27]
Looks like on a NixOS system using Nix 2, we need to set `NIX_REMOTE=daemon` (as with any use of Nix 1.11 on Nix 2), or perhaps switch the 'nix' used to 'nixUnstable'?

Anyway would be good to ensure this worked with the upcoming 18.03 release :).

Thanks!

**Comment by dtzWill** [comment]
This seems to only be a problem when using nix-bundle as built by `release.nix`, for whatever reason? Sorry if this is a non-issue :).

**Comment by matthewbauer** [comment]
I think this is fixed by @cleverca22's changes:

```
$ nix-bundle bash /bin/sh
$ echo $NIX_REMOTE

$ NIX_REMOTE=daemon ./sh
/ > echo $NIX_REMOTE
daemon
/ > exit
exit
```
