### ISSUE TITLE
Getting execvp errors when running binaries on another machine

### ISSUE THREAD

**Issue by georgewsinger** [matthewbauer/nix-bundle#58]
I used nix-bundle to make various binaries on an Ubuntu 19.04 machine with `nix` installed:

```shell
cd~
git clone https://github.com/matthewbauer/nix-bundle.git
cd nix-bundle
nix-shell

cd /path/to/new/directory
~/nix-bundle/nix-bundle.sh nixpkgs.xorg.xrdb
~/nix-bundle/nix-bundle.sh nixpkgs.wmctrl
~/nix-bundle/nix-bundle.sh nixpkgs.terminator
~/nix-bundle/nix-bundle.sh nixpkgs.xpra
```

The problems are as follows:

1.  **On my Ubuntu machine, the static binaries only work if they are executed within the folder which they were generated.** For example, if I switch from `/path/to/new/directory` to `/path/to/new` and run i.e. `./directory/terminator`, then I get `execvp` errors like

 ```shell
execvp(/nix/store/y6m5r6pwa63vhmywmcmwkkbm15v44jm4-terminator-1.91/bin/terminator): No such file or directory
```

2.  **If I tarball and send the binaries to another machine (running ArchLinux), then none of them work.** No matter what directory the binaries are ran in, I get `execvp` errors like:

 ```shell
$ ./terminator
execvp(/nix/store/y6m5r6pwa63vhmywmcmwkkbm15v44jm4-terminator-1.91/bin/terminator): No such file or directory
$ ./wmctrl -l
execvp(/bin/wmctrl): No such file or directory
```

 Some of the errors mention `/nix/*` paths, while others don't. In case relevant: the Arch machine doesn't have `nix` installed.

**Comment by matthewbauer** [comment]
This should be fixed with 2a8b914e1b14706a0d3bbc5f8f43af624ef48183
