### ISSUE TITLE
Not working on first try

### ISSUE THREAD

**Issue by k0001** [matthewbauer/nix-bundle#6]
I tried `nix-bundle`ing `hello` following the instructions, but it doesn't seem to work.

```
% nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/378662bbba6142ffee9fce02136f70d3d96209c2.tar.gz -p hello --run "./nix-bundle.sh hello \$(which hello)" && echo "done bundling" && ./hello
Nix bundle created at hello.
done bundling
execvp(/nix/store/7984c712x8ksg6c26jdggg2zxf0ilymg-hello-2.10/nix/store/b705xbm1nchiwj6cfnkjwi0lnnr8hnri-hello-2.10/bin/hello): No such file or directory
```

The `nixpkgs` version being used is a recent NixOS-16.09 version.

**Comment by probonopd** [comment]
I also need to run the commands multiple times until they succeed sometimes. Would be great if this could be fixed, since it effectively prevents automation.

**Comment by matthewbauer** [comment]
@k0001 I think the issue is that ```which hello``` is not going to work. The path should be relative to the nix output path: so /bin/hello.

So try:
```
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/378662bbba6142ffee9fce02136f70d3d96209c2.tar.gz -p hello --run "./nix-bundle.sh hello /bin/hello" && echo "done bundling" && ./hello
```

**Comment by matthewbauer** [comment]
I've update the the README to be a little more specific.
