### ISSUE TITLE
Crashes with "[...]-startup: No such file or directory"

### ISSUE THREAD

**Issue by srid** [matthewbauer/nix-bundle#63]
Running the neuron bundle results in:

```
/tmp/tmpx-2f521268c1050713/dat/../run: line 1: ./nix/store/pn84j5vljjkxxgwk2fjfm3cvpg8rc2wr-startup: No such file or directory
```

To reproduce:

1. [Install neuron](https://neuron.zettel.page/2011501.html) using Nix
1. Create the bundle: `./nix-bundle.sh neuron $(which neuron)`
1. Run the bundle: `./neuron --help`
1. It will crash with the above error

## Environment

```
20.09pre228622.029a5de0839 (Nightingale)
```

**Comment by Thra11** [comment]
If you've installed neuron, doesn't `$(which neuron)` return something like `/run/current-system/sw/bin/neuron`, whereas I believe nix-bundle wants the path of the the binary relative to the neuron output, e.g. `/bin/neuron`?

**Comment by srid** [comment]
Uhh, you are right. Don't know why I ran it that way. Okay, trying differently:

```
./nix-bundle.sh ./result /bin/neuron
```

(Note: I'm using `./result` so as to use the result of the project's `nix-build`).

This results in a different error:

![image](https://user-images.githubusercontent.com/3998/85148637-5f8c1380-b21e-11ea-9bbd-54044d5b5e08.png)

Why does it fail to find it when it obviously exists?

**Comment by srid** [comment]
The bundle does not contain the executable it seems:

```
srid@thebeast /t/nix-bundle (master)> du -sh neuron
13M     neuron
srid@thebeast /t/nix-bundle (master)> du -sh /nix/store/c9zdsf8f9d6c5pvs1x3gz13mj112m8g6-result/bin/neuron
139M    /nix/store/c9zdsf8f9d6c5pvs1x3gz13mj112m8g6-result/bin/neuron
srid@thebeast /t/nix-bundle (master)>
```

**Comment by srid** [comment]
Ah, so you have to use `readlink ./result`. Now the executable size has changed a bit (only a bit):

```
srid@thebeast /t/nix-bundle (master)> du -sh neuron
37M     neuron
```

But it still fails to run:

```
srid@thebeast /t/nix-bundle (master) [SIGINT]> ./neuron --version
./nix/store/08qgpp9l5607j6g4wfjq9zafnxd45qhh-startup: line 2: ./nix/store/jg5zmbmgq596hzydjscwgck5hrjvw8rv-nix-user-chroot-2c52b5f/bin/nix-user-chroot: No such file or directory
```

**Comment by Thra11** [comment]
> Why does it fail to find it when it obviously exists?

One of the joys of libc (I think it's a libc thing? might be glibc) is that it doesn't have a proper way to report _can't find_ errors to the user, so "No such file or directory" doesn't actually tell you _which_ file or directory it couldn't find. Last time I was messing around with nix-bundle, I remember getting a similar error: it turned out to be the executable interpreter, `ld-linux.so`, which it couldn't find.

IIRC, you can run `./neuron --extract`, which will dump the bundle contents. This can help to work out what actually is and isn't in the bundle.

**Comment by srid** [comment]
FWIW this is what I see in the extracted contents (I note not all deps are in the bundle?)

![image](https://user-images.githubusercontent.com/3998/85153381-2656a200-b224-11ea-8c98-7fe418ac7782.png)

**Comment by srid** [comment]
But the since the not-exists error happened on `nix-user-chroot`, this one instead may be more relevant?

![image](https://user-images.githubusercontent.com/3998/85153650-6f0e5b00-b224-11ea-9642-7116d7355c68.png)

**Comment by srid** [comment]
Got it working with IFD from cli:

```
./nix-bundle.sh '(import ../neuron)' /bin/neuron
```

**Comment by matthewbauer** [comment]
So with import works, but without import fails? That sounds like we may not be getting references correctly. I wonder if exportReferencesGraph is somehow failing here.
