### ISSUE TITLE
Provide a small(er than Firefox) graphical app as an example

### ISSUE THREAD

**Issue by ThibaultLemaire** [matthewbauer/nix-bundle#65]
Firefox is a big beast (and potentially not the safest to run, see #53), I thought I would find a smaller package to demonstrate graphical apps.

[Here are some patches to apply to the README](https://github.com/matthewbauer/nix-bundle/files/5144282/add-examples-patch.tar.gz) (I'm sorry I was too lazy to setup a whole fork and RSA keys, etc. I hope you don't mind.)

I also found a game to showcase SDL compat as well. (As a wannabe indie game developer who doesn't want to bother with packaging for every Linux distro out there, I'm very interested in SDL support. I thought others might be too.)

**Comment by matthewbauer** [comment]
Looks good, applied in d62327676e5e673117d88e30d6ccab15657edcc3 and 83742ac8ea4230ca239f948a6b2127449b25ece8.

**Comment by ThibaultLemaire** [comment]
For the record, I've successfully tested `xskat` and `ivan` executables on `NixOS 20.09 (Nightingale) x86_64` (The machine that bundled them), `Debian `GNU/Linux 9 (stretch) 64-bit` as well as `Manjaro KDE 20.0.3` (VM). I couldn't get them to work with Fedora (VM). I suspect that's to do with wayland and/or kernel permissions. I'll have to do some more tests.
