### ISSUE TITLE
... is not allowed to refer to a store path

### ISSUE THREAD

**Issue by DavHau** [matthewbauer/nix-bundle#68]
On current master (c5f2dfc73609412bc545b88b75947ebca799c4c6), nix-bundle seems to be broken.

`./nix-bundle.sh hello /bin/hello`
errors out with:
```
the string '/nix/store/9pqfirjppd91mzhkgh8xnn66iwh53zk2-hello-2.10' is not allowed to refer to a store path (such as '!out!/nix/store/pyb210y8vqvd6maifaja58a3bl19wazs-hello-2.10.drv')
```

I assume this due to this change:https://github.com/matthewbauer/nix-bundle/pull/67
I didn't debug it any further.

**Comment by georgyo** [comment]
@matthewbauer @zimbatm I can confirm that rolling back that merge fixes this problem.

**Comment by zimbatm** [comment]
fixed in https://github.com/matthewbauer/nix-bundle/pull/70 . Sorry for the breakage!
