### ISSUE TITLE
Nix-bundle is currently broken in nixpkgs

### ISSUE THREAD

**Issue by takeda** [matthewbauer/nix-bundle#84]
Recently nixpkgs removed lib from stdenv. I saw that fix for this was merged, but nix-bundle in nixpkgs is still version 0.4.0 which is broken. Any idea when a new version will be released and nixpkgs will be updated to use it?

**Comment by matthewbauer** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/144279
